# Generated by Django 6.0.5 on 2026-05-16 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('not_informed', 'gender_not_informed'), ('male', 'gender_male'), ('female', 'gender_female'), ('other', 'gender_other')], default='not_informed', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('default_language', models.CharField(choices=[('pt-BR', 'language_pt_br'), ('en', 'language_en')], default='pt-BR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
